version: "3"

volumes:
  pgadmin_data: {}

services:
  accounts-sv1:
    container_name: accounts-sv1
    image: accounts-sv1
    env_file: .env
    ports:
      - "8001:8081"
    build:
      context: ./
      dockerfile: Dockerfile.accounts

  accounts-sv2:
    container_name: accounts-sv2
    image: accounts-sv2
    env_file: .env2
    ports:
      - "8002:8081"
    build:
      context: ./
      dockerfile: Dockerfile.accounts

  operations-sv:
    container_name: operations-sv
    image: operations-sv
    env_file: .env
    ports:
      - "8009:8081"
    build:
      context: ./
      dockerfile: Dockerfile.operations

  commission-sv1:
    container_name: commission-sv1
    image: commission-sv1
    env_file: .env
    ports:
      - "8011:8081"
    build:
      context: ./
      dockerfile: Dockerfile.commission

  cashbacks-sv1:
    container_name: cashbacks-sv1
    image: cashbacks-sv1
    env_file: .env
    ports:
      - "8012:8081"
    build:
      context: ./
      dockerfile: Dockerfile.cashbacks

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -Xms128m -Xmx256m
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_HOSTNAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
